apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.26.225-192.168.26.235

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-ip-pool