apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    fullnameOverride: loki
    persistence:
      enabled: false
    config:
      table_manager:
        retention_deletes_enabled: false
