apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "6.42.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    fullnameOverride: loki
    deploymentMode: single
    persistence:
      enabled: false

    loki:
      auth_enabled: false
      useTestSchema: true
      server:
        http_listen_port: 3100
      storage:
        type: filesystem
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
