apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "6.42.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    fullnameOverride: loki
    deploymentMode: SingleBinary
    persistence:
      enabled: false

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      limits_config:
        allow_structured_metadata: true
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
      schemaConfig:
        configs:
          - from: "2025-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ruler:
        storage:
          type: local
          local:
            directory: /tmp/rules
      server:
        http_listen_port: 3100

    singleBinary:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
