apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: wordpress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  defaultBackend:
    service:
      name: default-backend
      port:
        number: 80
  rules:
    - host: app.local
      http:
        paths:
          - path: /wp-admin
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
          - path: /wp-login.php
            pathType: Exact
            backend:
              service:
                name: wordpress
                port:
                  number: 80
          - path: /wp-content
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
          - path: /wp-includes
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
          - path: /wp-json
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
          - path: /wp-admin/admin-ajax.php
            pathType: Exact
            backend:
              service:
                name: wordpress
                port:
                  number: 80
