apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:XEz2vvpkdg==,iv:D79jDpRC5CqZPWuyuJt99ECykEpDj0mqSObR2Bdm/uI=,tag:LFiwWd4q2IxRPzNP2Qj1Hw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:Wd3DCFLZTdQ1dmZT6MMO,iv:TsfT8FvQGiHCihA6c/PK07DGdWL7i6b/X0avJ0Vws5g=,tag:xB3LYjqagr1i2xpr86lvSw==,type:str]
    db-name: ENC[AES256_GCM,data:hWLL6Q+jCcYV,iv:diVLdqVNj8ZJHthgIOUnXJXNuS+hOer4QUebXV/PoXA=,tag:TL4gG7Jqz4dUeS03P29dXA==,type:str]
    db-host: ENC[AES256_GCM,data:dKKu15gfV9mjcNT2S7KURvAhE0Hv02DICC2QUKQ=,iv:LdJUliBCw0ozasX6brADC0CpSv9jwVk66d/V+6iqur8=,tag:7IsFlpRMgKTS339lM/CaeA==,type:str]
sops:
    age:
        - recipient: age15c0cxyvg7h3zz53j8hg7famfns3yh2zth956tsvu5525u29wzggsty2wjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bCt0T0d2eStPcit4VjlY
            ZVhzeTU4cmFQdkZ1Y0FTd3VGUTBLRkFybUNZCnJuQUVJbThCVXdEOXhsRk5BQXhU
            UWc5amdQWk10WjJMdnlwQVpmRWgzLzgKLS0tIDcyWVlaUERNVEwxUVQ2cU9mQTVl
            d3VDTm1ocW1tNm5zbGR4UGV4QU9RQ1EKOoz3BZTF2EKeBiXVv3JikuE8vDBELzSK
            SrJHtoDq6hgXkZSJMDdLz1+EvPU+NyQa2e53nwOIj+I8irRJaovohg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T09:24:07Z"
    mac: ENC[AES256_GCM,data:l74jq8j5T/MEYe68sbwtemKpjly3deYyHHVqQ8K1iEayOoYZFG75B/az7uq6kfelmhbq1IheagmayXn/6bxS7aC3WP+GYWcEYXP4vHstp6zfreAJGCe0c4wGECEL+TBxxYpF4630cB8HrdBBsQffpmC3X0u2QRZwZnl/MCIvo0A=,iv:PmeY8djFjIxzMKpcCXDA61fHKVw5BNqTlHjrYLbdklc=,tag:Wie5WcZu2uWSTVJRWp4rEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-admin
    namespace: wordpress
type: Opaque
stringData:
    wordpress-username: ENC[AES256_GCM,data:gjC2xsA=,iv:/xCk43Rl8Y0IZ186zpHcvT6XNtIoMNnmcG5oNsUsc7w=,tag:mDiM8v8X4SGeDzodvIrlyw==,type:str]
    wordpress-password: ENC[AES256_GCM,data:Zeq8EECyExNpxfF/4MW5,iv:g4932IlJperveqLMlt1UYB1x9mXp9l6soMYLRQltV6o=,tag:lqM9wCsNRx+aOXCdgm5XVQ==,type:str]
    wordpress-email: ENC[AES256_GCM,data:o2xeFpG9GB4gaeFM74OUcYc=,iv:k1GKy0E4f6wQEI7At5R+I76WKegre0fh+n/OHttxPKM=,tag:xpaArZxP2hozUNTKyXv28A==,type:str]
sops:
    age:
        - recipient: age15c0cxyvg7h3zz53j8hg7famfns3yh2zth956tsvu5525u29wzggsty2wjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bCt0T0d2eStPcit4VjlY
            ZVhzeTU4cmFQdkZ1Y0FTd3VGUTBLRkFybUNZCnJuQUVJbThCVXdEOXhsRk5BQXhU
            UWc5amdQWk10WjJMdnlwQVpmRWgzLzgKLS0tIDcyWVlaUERNVEwxUVQ2cU9mQTVl
            d3VDTm1ocW1tNm5zbGR4UGV4QU9RQ1EKOoz3BZTF2EKeBiXVv3JikuE8vDBELzSK
            SrJHtoDq6hgXkZSJMDdLz1+EvPU+NyQa2e53nwOIj+I8irRJaovohg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T09:24:07Z"
    mac: ENC[AES256_GCM,data:l74jq8j5T/MEYe68sbwtemKpjly3deYyHHVqQ8K1iEayOoYZFG75B/az7uq6kfelmhbq1IheagmayXn/6bxS7aC3WP+GYWcEYXP4vHstp6zfreAJGCe0c4wGECEL+TBxxYpF4630cB8HrdBBsQffpmC3X0u2QRZwZnl/MCIvo0A=,iv:PmeY8djFjIxzMKpcCXDA61fHKVw5BNqTlHjrYLbdklc=,tag:Wie5WcZu2uWSTVJRWp4rEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
