apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/prometheus-community/charts/prometheus
  interval: 1m
  secretRef:
    name: dockerhub-cred