apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: "14.0.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      existingSecret: mysql-auth
      username: wp_user
      database: wordpress
    primary:
      persistence:
        enabled: false 
