apiVersion: v1
kind: Service
metadata:
  name: default-404-backend
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: default-404-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-404-backend
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-404-backend
  template:
    metadata:
      labels:
        app: default-404-backend
    spec:
      containers:
      - name: default-backend
        image: nginx:alpine
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: default-backend-config
      - name: html
        configMap:
          name: default-backend-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-backend-config
  namespace: ingress-nginx
data:
  default.conf: |
    server {
        listen 80;
        location / {
            return 302 https://www.google.com;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-backend-html
  namespace: ingress-nginx
data:
  index.html: |
    <html>
    <head><title>Redirecting...</title></head>
    <body>
    <h1>Redirecting to Google...</h1>
    </body>
    </html>