apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
      controller:
        allowSnippetAnnotations: true
        service:
          type: LoadBalancer
          externalIPs: []
        config:
          proxy-intercept-errors: "true"
        extraVolumes:
          - name: lua-404
            configMap:
              name: ingress-lua-404-redirect
        extraVolumeMounts:
          - name: lua-404
            mountPath: /etc/nginx/lua
            readOnly: true
        serverSnippet: |
          error_page 404 = @redirect_google;

          location @redirect_google {
              access_by_lua_file /etc/nginx/lua/404-redirect.lua;
          }