===== cluster/infrastructure/ingress-nginx/helmrelease.yaml =====
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      allowSnippetAnnotations: true
      service:
        type: LoadBalancer
        externalIPs: []
      
      # Mount Lua scripts (unchanged)
      extraVolumes:
        - name: custom-lua-scripts
          configMap:
            name: ingress-nginx-lua-404  # Wait, mismatch! Your ConfigMap is "ingress-lua-404-redirect"
            defaultMode: 420
      
      extraVolumeMounts:
        - name: custom-lua-scripts
          mountPath: /etc/nginx/lua/plugins/custom/
          readOnly: true
      
      # Global config: Enable Lua loading (add this if not present)
      config:
        lua_shared_dicts:  # Optional: For shared memory if needed later
          my_dict: 10m
        server-snippet: |
          # Load and run Lua for every server block (virtual host)
          # For learning: This runs in the server context, before location matching
          access_by_lua_block {
            -- Require the mounted Lua file (path: /etc/nginx/lua/plugins/custom/404-redirect.lua)
            -- Nginx Lua loader searches /etc/nginx/lua/ by default
            local redirect_handler = require("plugins.custom.404-redirect")
            redirect_handler()  -- Call it (your script uses 'return', so it executes directly)
          }

          # Your original comment (can remove or keep for WordPress paths if you revert later)
          # WordPress admin paths - proxy to WordPress