apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      allowSnippetAnnotations: true
      service:
        type: LoadBalancer
        externalIPs: []
      
      # Mount Lua scripts
      extraVolumes:
        - name: custom-lua-scripts
          configMap:
            name: ingress-nginx-lua-404
            defaultMode: 420
      
      extraVolumeMounts:
        - name: custom-lua-scripts
          mountPath: /etc/nginx/lua/plugins/custom/
          readOnly: true
      
      # Location-based routing configuration
      config:
        server-snippet: |
          # WordPress admin paths - proxy to WordPress
          location ~* ^/(wp-admin|wp-login\.php|wp-json) {
              proxy_pass http://wordpress.wordpress.svc.cluster.local;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
          
          # Root path - proxy to WordPress
          location = / {
              proxy_pass http://wordpress.wordpress.svc.cluster.local;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
          
          # All other locations - redirect to Google via Lua
          location / {
              access_by_lua_block {
                  local redirect = require("404-redirect")
                  redirect.redirect_to_google()
              }
          }