apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      allowSnippetAnnotations: true
      service:
        type: LoadBalancer
        externalIPs: []
      
      # Keep the volumes for Lua scripts (but remove the duplicate lua_package_path)
      extraVolumes:
        - name: custom-lua-scripts
          configMap:
            name: ingress-nginx-lua-404
            defaultMode: 420
      
      extraVolumeMounts:
        - name: custom-lua-scripts
          mountPath: /etc/nginx/lua/plugins/custom/
          readOnly: true
      
      # Remove the http-snippet with duplicate lua_package_path
      # But keep the server-snippet with the Lua execution
      config:
        server-snippet: |
          rewrite_by_lua_block {
            local redirect_404 = require("404-redirect")
            local ok, err = pcall(redirect_404.redirect_404)
            if not ok then
              ngx.log(ngx.ERR, "Error in 404 redirect Lua script: ", err)
            end
          }