apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      allowSnippetAnnotations: true
      service:
        type: LoadBalancer
        externalIPs: []
      # Updated configuration for reliable 404 handling
      config:
        http-snippet: |
          location @redirect_404 {
            return 302 https://www.google.com;
          }
        server-snippet: |
          error_page 404 = @redirect_404;