# cluster/infrastructure/ingress-nginx/lua-404-configmap.yaml (update for consistency)
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-lua-404-redirect
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    -- Simple redirect (matches embedded version)
    return ngx.redirect("https://www.google.com", 302)