apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-lua-404-redirect
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    if ngx.status == 404 then
      return ngx.redirect("https://www.google.com", 302)
    end
