apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-lua-404-redirect  # Note: Your ConfigMap name is this, but file is 404-redirect.lua
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    -- Always redirect to Google (for learning: this runs in access phase)
    return ngx.redirect("https://www.google.com", 302)