apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-lua-404-redirect
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    local uri = ngx.var.uri
    if uri == "/" or uri:match("^/wp%-admin") or uri:match("^/wp%-login%.php") then
        return
    end
    return ngx.redirect("https://www.google.com", 302)
