apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-lua-404
  namespace: ingress-nginx
data:
  404-redirect.lua: |
    local _M = {}
    
    function _M.redirect_404()
        local uri = ngx.var.uri
        local request_uri = ngx.var.request_uri
        
        ngx.log(ngx.INFO, "Checking 404 redirect for URI: ", uri, " Request URI: ", request_uri)
        
        -- Skip redirect for essential WordPress paths
        if uri == "/" or uri:match("^/wp%-admin") or uri:match("^/wp%-login%.php") or uri:match("^/wp%-json") then
            ngx.log(ngx.INFO, "Skipping redirect for WordPress path: ", uri)
            return
        end
        
        -- Check if this is a 404 or if WordPress is about to add trailing slash
        if ngx.status == 404 or (ngx.var.request_uri and not ngx.var.request_uri:match("/$") and ngx.var.uri ~= "/") then
            ngx.log(ngx.INFO, "Redirecting to Google: ", uri)
            ngx.redirect("https://www.google.com", 302)
            return
        end
    end
    
    return _M